environment:
  - city hall


story beats:
  - Jam returns to the sheriff's station, located within City Hall, after the encounter with the killer twins.
    Charlaine is looking up from her files, and Jam nods to her as greeting.
    Jam is exhausted and still dehydrated, immediately inhaling an entire pot of drip coffee to replenish himself.
    The caffeine helps him absorb the liquid faster, providing a temporary boost and speeding up recovery. Jam
    drops into his chair and for the millionth time wishes he could enjoy a cigarette. Alas, Nicotine has no 
    effect on him.
  - Jam instructs Charlaine to get "her kit" while he's caffeinating. The deputy assumes he means fingerprinting
    equipment, but Jam corrects her, indicating they needs the kit for investigating traces of magic. He tries to
    makes a joke about Charlaine calling on her daddy for help. Charlain rolls her eyes and replies that she isn't
    exactly into "Papa Legba", the guardian of the crossroads, that's more something her Grand-Mère deals with.
  - As Jam waits for the deputy to fetch the magic investigation kit, the mayor's voice starts coming out 
    of the desk speaker. Anna requests Jam's presence in his office as soon as possible. Jam sighs and gets out
    of the chair. He checks his appearance in a small mirror on the wall. Charlaine jokes about that he looks good 
    enough for his "amour non partagé", implying that Jam has the hots for the mayor. Jam only grunts but admits to 
    himself that he had that coming given the "daddy" joke. He grumbles about insubordination being a fireable offense,
    to which Charlaine just smiles and responds, "love you, too."
  - Jam heads next door to the mayor's office. [describe the mayor's office to set the scene]. As he approaches the desk,
    Anna starts to cough and tells Jam that he sinks of garlic. Jam sheepishly apologizes nand replies that he always
    carries a clove in a ziploc bag, in case he needs to break up a bar fight at the Fangs and Fur. One of the bullets 
    must have nicked the plastic and now the smell is streaming out.
  - At the mention of bullets, Anna asks Jam about the progress of the investigation.
    Jam summarizes the events and explains the involvement of teleportation magic. Jam mentions that this had been
    the first sign that non-human elements might be involved and that it complicates things.
  - The mayor frowns at the mention of magic and mentions calling in additional resources.
    Jam grudgingly agrees that bringing in outside help might be necessary if magic is involved.
    The mayor corrects Jam that it’s not a question of necessity but of the law.
  - Jam expresses his desire to continue the investigation before "guys with suits and sunglasses" start
    interfering and potentially destroying evidence. He mentions that he might have to call in on Anna's "Igor".
    Anna reproaches Jam for the slur and clarifies that, yes, Krabat is helping her with some research, but that
    doesn't make her Frankenstein and him Igor. Jam stoically ignores the criticism.
  - Jam summarizes that they probably have one, two days max before the "suits" turn up, and that he will try to 
    figure out as much as he can before that. Anna's attitude changes to that of an empathetic, concerned friend. She
    reminds Jam that the town has invested significant money in legal fees to prevent a repeat of past incidents. No
    government entity will ever try to confiscate their Sheriff ever again. Jam acknowledges the reminder with a nod,
    indicating his understanding of the situation. He knows that "the town" in this context is Anna, given that the
    city coffers are notoriously empty. Without Anna Arborio, this town would be dirt poor.
  - Jam leaves the mayor's office, determined to continue his investigation despite the impending involvement
    of outside authorities. He knows he needs to act fast before any potential evidence is compromised. He returns to his
    office where Charlaine is packed up and ready to go. Jam notices that she has set up another pot of coffee, and
    he gulps the liquid down. Then, they open the door and head out to start the investigation.

