# Chapter specific configuration

# The beats for this chapter
story beats:
  - Jam said, "And then he told me to come here before you open the mail."
    Jam and Anna are sitting in the mayor's office at city hall. The place is still
    a mess, but Anna has at least managed to clean up the guest chair and enough of
    the desk to have space for Jam's pot of steaming coffee. Jam drinks directly from
    the pot, not bothering to transfer it into a mug. Having told Anna everything that 
    happened so far, Jam puts down the pot and waits for the Anna's reaction.
  - Anna recaps the situation - Charlaine is gone, Krabat is gone, and an ancient voodoo
    deity has sent Jam on a quest to find some missing person. If Jam does so, then Papa
    Legba will somehow help getting Charlaine and Krabat back. Jam concurs with the summary.
  - Anna sighs and pulls a little flask out of her drawer. Before Jam can intervene,
    she takes a swig. She notices the expression on Jam's face and tells him to relax.
    She tells him that the flask only contains pig's blood, which tastes like crap but
    at least is not addictive. Jam shrugs and reminds her that old habits die hard, 
    even after years. Anna nods and points at her fifty year chip. 
    One day at a time, she replies.
  - Jam takes another sip of coffee and asks Anna what she makes of the situation. Anna
    replies that we can conclude that Krabat is as much a victim as Charlaine. 
    Anna knows that Jam had suspicions about Krabat, but she argues that this encounter prooves 
    that he is not behind this. After all, Krabat's source of magic  is very different
    from Voodoo. Jam does not agree but does not press the matter.
  - Anna continues that she is still confused by Legba's involvement. If he was behind 
    the recent series of murders, why would he task Jam to find someone? Why not just
    do it himself? Jam considers this. He counters that Legba did not admit to anything,
    he just did not deny anything either. Being a trickster god, his schemes might be hard to 
    anticipate. That being said, Jam had the impression that Legba genuinely wanted
    that person saved. If he didn't do it himself, that meant he couldn't directly interfere.
    Which could mean many things. For example, there might be different factions in his
    cult and he cannot play favorite. Another explanation could be that another deity 
    is involved and he has to go through proxies.
  - There is moment of silence where Jam and Anna mull this over. Anna asks, "so, 
    this guy spends you on the quest but doesn't give you any details? No godly 
    weapon or a magic compass that shows you the way?" Jam nods and responds that all
    that Legba told him was come to city hall before the mayor opened her mail.
    Anna and Jam stare at the half dozen letters on Anna's desk. Anna sighs and grabs a
    letter opener. "Let's get to it, then," she says and reaches for the first letter.
  - Jam watches Anna pick up the first letter on her desk. It was a standard business envelope,
    cream-colored and plain. No return address, just a single, ordinary stamp.
    The only thing out of the ordinary is that it has a wax seal. Beyond that, 
    it looked utterly unremarkable, the kind of envelope that gets buried under a 
    pile of bills and forgotten.
  - Being on alert after Jam's report, Anna holds the envelope close to the desk lamp, 
    scrutinizing it from all angles. It looked completely ordinary, even under the harsh light.  
    With a sigh, she decided to just open it. As her finger pressed down on the seal, 
    a faint click resonated from within the envelope. Before they could react, a muffled pop 
    echoed through the office. A shimmering cloud of multicolored glitter erupted from the envelope, 
    momentarily blinding them.
  - Jam sputtered, "What the…", coughing a cloud of glitter out of his mouth. Anna blinked rapidly, 
    waving away the sparkling dust. "Glitter bomb?" she asked incredulously. They looked back at the 
    envelope, now lying split open on the desk. The interior was still plain, no hidden compartments, 
    no scorching marks. Just harmless, sparkly chaos. But beneath the glitter, nestled in the folds of the 
    envelope, lay a tiny, intricately carved wooden doll. On the smooth back of the doll,
    a single name was etched in a delicate script -- Charlaine Meyers.
  - Jam picks up the doll. Now that he thinks about it, it all makes sense. Charlaine's grandmother was
    pretty high up in the local church, it made only sense that she had made some precautions to protect
    her grandchild. He puts the doll back on the table. The doll lays still for a moment, then starts to turn
    about 45 degrees to face in the same direction it had been looking before. Jam rotates the doll again,
    and the doll turns back towards the same directon. "I guess there's our magic compass," Jam laughs.
  - Charlaine grabs an empty petri dish and lays the tiny doll inside of it. She gets up and walks across 
    the room. Like a home-made water compass, the doll keeps pointing into the same direction.
    Charlaine hands the compass to Jam. "Go bring them back," she says.

# What of the given sceneries in the parent YAML does this chapter play in?
environment:
  - city hall

characters:
  Anna Arborio:
    Mayor and town doctor of Shadow Falls, Anna has a complicated relationship with Jam.
    Anna is a vampire, but she has not fed on humans in many decades. Jam is actually her
    AA sponsor and a good friend.  On the other hand, Jam's need to protect the town and 
    Anna's ambitions for the community are sometimes at odds. Anna has pitch black hair, 
    very fair skin, and bloodshot eyes because she works through the day and does not
    spend enough time in her coffin. She tries to hide her eyes behind sunglasses and
    has also banned any mirrors from her office. Jam has a romantic interest in Anna,
    but the feeling is not mutual. The same is true for Krabat.
  Papa Legba:
    Also calls himself Eshu or Elegba. Papa Legba is an ancient god of the Fon people,
    a West African ethnic group, though he is better known through his place in voodoo
    religion. Legba is often referred to as a trickster god, like Loki or Coyote. He 
    has the ability to traverse seamlessly between the mortal and divine realms. He often 
    serves as a mediator between the realms. He is often portraied as an old man with
    a walking stick in tattered clothing. Elegba is fond of dogs and has a giant hound
    as a pet. He has a vested interest in Charlaine, since her grandmother is one of
    his devout followers and Charlaine displays an aptitude for magic. Jam amuses him,
    and he is willing to overlook minor transgressions like Jam calling him Daddy
    Longlegs.
