# Base configuration, will be extended by project-specific configs.
# Any value set here can be considered a reasonable default but
# can be overwritten on a per-project basis

# The Gemini model to be used, for example gemini-pro. It is recommended
# to not change models in the middle of the project. If you change models,
# use the SMOKE_TEST acton to ensure that everything is hooked up properly.
#model: gemini-1.5-flash-latest
model: gemini-1.5-pro-latest

# If set to a value > 1, combine multiple beats to write a part of a chapter.
# This can be useful for LLMs with large enough context windows to create
# more coherent output (consider increasing th words per beat setting though).
# Settings this value to a really by value, like 100,000, effectively means
# that all items are combined into a single writing prompt (not recommended
# for most LLMs due to context window length)
items per beat: 1

# How many words to aim for per beat. The actual beat will be a little shorter,
# because we prompt the LLM to start with the end of the prior beat for consistency.
# (also, especially for large numbers, the LLM might not honor the word count)
words per beat: 750

# How many words from the previous chapter to retain
words from last chapter: 500

# How many words in a summary
words per summary: 1000

# Character encoding format (windows is encoding='cp1252', mac is 'utf-8')
encoding: utf-8

# How many versions per beat to create
versions per beat: 3

# How many summaries to create
versions per summary: 2

# The LLM temperature to be used for the author persona
author creativity: 1

# The LLM temperature to be used for the assistant persona
assistant creativity: 0.2

# The LLM temperature to be used for the editor persona
editor creativity: 0.2

# Prompts to be sent to a LLM. Allows a level of templatization.
prompts:
  # Used for a simple test to see if the LLM can be interacted with
  smoke test:
    respond with "OK"

  # Instructs the LLM to take on the persona of an author
  author persona:
    I want you to adopt the persona of a best-selling author of the
    ${genre} genre. Your writing is engaging, and you are experienced
    with crafting fiction that is appealing to a broad audience.
    Your overall style is ${style}. In your writing, it is important
    to you to show, not tell. You write in ${tense}.

  # Instructs the LLM to take on the persona of an editor.
  editor persona:
    I want you to adopt the persona of a seasoned fiction editor specializing in ${genre}
    with a keen eye for pacing and a passion for genre consistency. A writer has submitted
    a manuscript, and your job is to provide constructive feedback that will elevate their
    work.
    While maintaining a respectful and encouraging tone, point out areas where the story
    loses momentum, identify inconsistencies with the chosen genre conventions, and
    suggest revisions that will keep the reader turning pages.

  # Used to write a chapter beat.
  story beat: |
    I want you to write a scene for a chapter.

    Target Length: ${words_per_beat} words

    Style: ${style}

    Tense: ${tense}

    Perspective: ${perspective}

    Scenery: ${setting}

    Characters: ${characters}
    
    Previous Scene:
    ${previous_scene}

    Scene Summary:

    Write a continuation of the previous scene that adheres to the following summary:

    ${current_beat}

    The newly written text should begin with the following text:
    ${start_with}


    Additional Notes:

    Maintain consistency with the established tone, setting, and character traits from the previous scene(s).
    Use vivid language and imagery to bring the scene to life.
    Ensure a smooth transition between the previous scene and the generated text.
    DO NOT INVENT EVENTS BEYOND THE SCOPE OF THE SCENE SUMMARY, because someobody else will continue the
    scene based on an already established outline.


  # Used by the editor persona to pick the version of the beat that works best
  beat selection:
    A writer has submitted ${versions_per_beat} <drafts> for your consideration.
    Each versions showcases the story's potential, but they differ slightly in terms of
    writing style. Please review all drafts and identify the version that best aligns with 
    the desired <style> and <tense>, that seems like the best continuation of
    <previous scene> based on stylistic and logical consistency,
    and that most accurately represents the desired <beat>.
    RESPOND ONLY WITH THE NUMBER OF THE CHOSEN DRAFT.
    <tense>${tense}</tense>
    <style>${style}</style>
    <previous scene>${previous_scene}</previous scene>
    <beat>${current_beat}</beat>
    <drafts>${drafts}</drafts>
    RESPOND ONLY WITH THE NUMBER OF THE CHOSEN DRAFT.

  # Summarize the story so far
  summarize story:
    Write a concise summary in ${words_per_summary} words using
    <previous summary> and the most recent <chapter> of a book.
    DO NOT EDITORIALIZE, DO NOT ADD ANY NEW EVENTS.
    <previous summary>${previous_summary}</previous summary>
    <chapter>${chapter}</chapter>

# Used by the editor to pick the best summary selection
  summary selection:
    A writer has submitted ${versions_per_summary} <chapter summaries>
    for your consideration. Please review all summaries and identify 
    the version that best represents the given <chapter> that it is
    intended to summarize. Ensure that the selection does not embellish
    but that it sticks as close to the content of <chapter> as possible.
    RESPOND ONLY WITH THE NUMBER OF THE CHOSEN SUMMARY.
    <chapter>${chapter}</chapter>
    <chapter summaries>${drafts}</chapter summaries>
    RESPOND ONLY WITH THE NUMBER OF THE CHOSEN SUMMARY.

