# Chapter specific configuration

# The beats for this chapter
story beats:
  - The chapter opens with Jam and Charlaine sprinting towards the silhouette of city hall 
    against the backdrop of a rising sun. The first rays of dawn paint the sky in vibrant hues of
    orange and pink. Panting and rain-soaked, they reach the steps just as the clock tower chimes
    five a.m. The heavy oak doors remain locked.
  - A sudden commotion distracts them. A short, middle-aged man in a rumpled suit stumbles out of
    an alleyway, pursued by three snarling, stray dogs. Charlaine, ever-resourceful, grabs a discarded
    brick and throws it, scattering the dogs. The man scrambles to his feet, clutching a battered 
    briefcase.
Scene 3: Introduction and Confusion

The man introduces himself as Herbert "Herb" Weatherby, here on behalf of the Mayor. He seems flustered and surprisingly grateful for their intervention.
Jam, suspicious and wary, invites Herb into the lobby for a much-needed rest. Charlaine, noticing his trembling hands, offers him a steaming cup of coffee from a nearby vending machine.
Scene 4: The Bureaucrat's Tale

Herb, visibly calmed, explains his role. He works for a clandestine government agency tasked with monitoring supernatural activity, a joint venture of the CIA and FBI (replace with "the agency" if you prefer).
He admits his superiors dismissed the Mayor's concerns about Shadow Falls as a "small-town spook story." He, however, dug through classified files and feels obligated to help.
Scene 5: Skepticism and a Spark of Hope

Jam remains unconvinced. He questions how a "paper pusher" like Herb could possibly be of any assistance.
Charlaine intervenes, reminding him about the map they were supposed to bring to city hall.
Jam retrieves the map, a flicker of hope igniting in his eyes.
Scene 6: Deciphering the Clue

Herb, to their surprise, recognizes the map as an old city survey with cryptic markings. He utilizes his knowledge of arcane symbols and hidden lore to decipher a section of the map.
This newly revealed information points them towards a specific location within the city, offering a potential next step in their fight against Legba.
Ending: A Tentative Alliance

The chapter concludes with a sense of cautious optimism. While Jam remains wary, he acknowledges Herb's knowledge might be a valuable asset. Charlaine, ever-pragmatic, reminds them they have no time to waste.
Additional Notes:

You can add details to the stray dog encounter, creating a tense and fast-paced opening. Describe the growls, the snapping jaws, and Charlaine's quick thinking with the brick.
Inject some humor into Herb's character. His nervous demeanor and fumbling with the briefcase can provide comic relief.
Consider adding a sense of unease. The city hall building itself could feel oppressive or ominous, hinting at the hidden dangers within.


# What of the given sceneries in the parent YAML does this chapter play in?
# List one or more...
environment:
  - city hall

# Optional changes to characters
characters:
  Herbert "Herb" Weatherby:
    Herb is a man built more for comfort than combat. He stands at a height slightly
    below average, with a bit of a paunch straining against the buttons of his ill-fitting
    suit. His thinning brown hair is meticulously combed over, a futile attempt to fight the 
    inevitable. His most distinctive feature is his pair of thick horn-rimmed glasses that 
    magnify his perpetually nervous blue eyes.
    Herb is the quintessential paper pusher. He thrives on routine, lost in a world of manila
    folders and cryptic regulations. He stumbles through life with a constant undercurrent
    of anxiety, convinced that any deviation from protocol will spell disaster. Despite 
    his nervousness, Herb possesses a keen intellect and a surprising wellspring of
    knowledge about the supernatural gleaned from years of processing classified files.
    Herb works for "the agency", a joint venture of CIA and FBI dedicated to supernatural
    cases. He is of low rank and does not have many friends at the agency, which is why
    he ended up with this case (his superiors did not want to waste valuable resources on
    a seemingly unimportant case in an unimportant town.)
