# Chapter specific configuration

# The beats for this chapter
story beats:
  - Thunder echoed through the concrete shell of the abandoned basement.
    The air hung heavy with the stench of mildew and a metallic tang that clenched at Jam's throat. 
    Towering over Charlaine, he swept the room with his flashlight for the last time.
    Despite his usual unflappable demeanor, the recent events gnawed at his gut.
  - Jam rumbled "See anything?", his voice low and steady. Charlaine shook her head, her brow furrowed in 
    concentration. Unlike Jam, she wasn't relying solely on sight. Reaching into a worn pouch on her belt, 
    she fished out a vial filled with shimmering dust; a pale lavender that seemed to glow faintly even in the 
    dim light. With a muttered incantation, she uncorked the vial and flung a handful of the dust into the air. 
    The dust swirled for a moment, then defied gravity, arcing gracefully through the air before converging in a 
    tight cloud near a dark stain on the dusty concrete floor.
  - Charlaine's eyes narrowed. With newfound purpose, she strode towards the spot, her boots crunching softly 
    on the debris-strewn floor. Kneeling beside the stain, she brushed away the dust to reveal the outline of a 
    broken bottle, its jagged edges glinting in the narrow beam of light. Beside it lay a single, worn leather
    rosette half-buried in the dirt. It shimmered faintly, catching the light in an unusual way. Unlike any 
    decoration Charlaine held, the leather was a deep, sun-bleached brown, weathered and cracked with age. 
    The intricate stitching, though faded, depicted a stylized claw, sharp and menacing.
  - Charlaine breathed turned the rosette over in her hand. "This is… strange."
    Jam crouched beside her, his gaze fixed on the rosette. 
    A slow grin tugged at the corner of his mouth.  "Wait a minute," he said,
    his voice tinged with excitement. "This looks kinda familiar…" 
    He reached into his pocket and pulled out a worn leather wallet. 
    Inside, nestled amongst faded IDs and credit cards, was another rosette, 
    identical to the one they'd just found. This one, however, still looked far newer, the leather supple 
    and the stitching bright. It depicted the same stylized claw, but with a bold inscription 
    circling it, "Fangs & Fur - 50th Anniversary."
  - Charlaine's eyes widened in realization. "Fangs & Fur? The bar down by the docks?"
    Jam chuckled. "The one and only. I got this years ago when they celebrated their big five-oh. 
    Guess someone from the bar must have ended up down here." Charlaine tucked the unearthed rosette into her pocket, 
    a new determination settling in her gaze. "Maybe," she said. "But the question is, why?"
    Jam responds that it's a weak lead, but still the best thing they got. "Let's go and have a drink, shall we?"
  - The rain pounded against the weathered exterior of Fangs and Fur as they stepped inside. 
    Warm light spilled from the saloon, welcoming them into a world of flickering lanterns and twangy country music. 
    Patrons, a mix of humans, shifters with subtle changes, and even a hulking troll nursing a mug of ale, 
    crowded around worn wooden tables. In the corner, hunched over a steaming plate of ribs, 
    was Krabat. He shot Jam a withering glance, the animosity between them simmering beneath the surface. 
    Charlaine, however, received a subtle nod from the mage, a hint of friendliness in his 
    usually stoic expression.
  - Jam and Charlaine approached the bar, the worn wood cool beneath their hands.
    Millie, the weathered bartender, greeted them with a tired smile. Jam ordered "the usual" and 
    Millie placed a bottle of Tequila in front of him.
    Charlaine, commenting that they are on duty, opts for a cappucino instead.
    Millie rumbled a good-natured, "This ain't no Starbucks, honey," 
    but shuffled over to the espresso machine anyway.
  - Charlaine took a cautious sip of her cappuccino, the frothy beverage a stark contrast to the
    rough-and-tumble atmosphere. Lowering her voice, she leaned towards Jam. "Alright, how do we approach this?"
    Jam shrugged, his expression stoic. "Casual. Ask around, see if anyone recognizes the rosette."
    Charlaine scanned the bar, her gaze settling on a group of burly men with tattoos. 
    Taking a deep breath, she pushed off the bar stool. "Excuse me, gentlemen," Charlaine began, 
    her voice polite yet firm. "Don't mean to bother you, but I was wondering if any of you might recognize this?"
    She pulled out the worn leather rosette, its sun-bleached brown catching the warm glow of the lanterns. 
    The men squinted at it, their conversation momentarily stalling. "Can't say I have, miss," rumbled a man with 
    a beard as thick as his arms. "Looks like some kinda old belt buckle."
    "Maybe a souvenir from a rodeo or somethin'," another man chimed in, a hint of amusement in his voice.
    Charlaine offered a smile that didn't quite reach her eyes. "Thanks anyway. Maybe someone else..."
  - Charlaine continued her circuit around the bar, showing the rosette to a weathered woman playing a 
    fierce game of pool, a lone troll nursing a mug of something considerably stronger than beer, 
    even the hulking bouncer by the door. Each encounter followed a similar pattern. 
    Furrowed brows, vague shrugs, and ultimately, no leads.
    Dejection settled in Charlaine's stomach. Returning to Jam, she reported her findings. 
    "No luck. Seems like nobody knows what this is."
    Jam took a swig of tequila, his face etched with contemplation. 
    "Maybe it's just an old bar giveaway, like my anniversary one. We could ask Millie..."
  - A deep voice cut through Jam's suggestion.  "Sheriff Slate," it drawled, laced with a faint 
    accent that sent shivers down Charlaine's spine.  They both turned to see Krabat standing 
    behind them, his tall frame casting a long shadow on the worn wooden floor. He turned to 
    Charlaine, a slight softening in his eyes, barely perceptible. 
    "Deputy Meyers. Heard you were poking around a strange case."
    Charlaine raised an eyebrow in Jam's direction. He nodded, a flicker of suspicion mingling 
    with the frustration etched on his face. The Mayor had mentioned sending Krabat, 
    but the timing seemed overly convenient. Krabat held up a hand, anticipating their questions.
    "Don't worry, I'm not here to meddle. I just happened to have a drink here when the two of
    you came in. May I?" he sais, pointing at the rosette.
  - The conversation gets interrupted when a Jam notices that a fight is about to break 
    out between two burly patrons. One, a human named Bruno, was a barrel-chested truck driver with a 
    shaved head and a perpetual scowl. The other, an ogre named Grog, was even a head taller,
    his thick green skin and wild beard making him a formidable figure. Through the shouting, Jam
    infers that the argument started when Bruno started to brag about his prowess in a recent 
    arm-wrestling contest. After a particularly outlandish claim about defeating a lumberjack 
    twice his size, Grog had had enough. "You wouldn't know an arm wrestle from a tea party," Grog sais.
    Bruno bristled. "You sayin' I'm a liar, green giant?" he roared, slurring his words slightly. "I'll show you a liar!"
    Millie, the bartender, threw her hands up in exasperation. "Not again!" she bellowed, but her voice 
    was lost in the rising tension.
  - Before anyone could react, Jam stepped forward. The arguing patrons dwarfed his humanoid form, 
    but he held his ground, his calm demeanor a stark contrast to the brewing storm. "Gentlemen," 
    he rumbled, his voice carrying a quiet authority that caused both Bruno and Grog to pause. 
    "Looks like the rain's got everyone a little on edge. Why don't we settle this like 
    civilized folk? Put down the fists, pick up a shot of Tequila. My treat." 
    Grog's beady eyes gleamed with a hint of amusement. He eyed Jam with a slow grin. 
    "Tequila, Sheriff? You sure about that? Millie only keeps the good stuff behind the counter, 
    the kind that costs more than me or Bruno make in a week."
    Bruno, still fuming, scoffed. "Yeah, right. Fancy sheriff liquor."
    Grog chuckled, a deep rumble that shook the floorboards.  
    "Now hold on there, Bruno. I ain't sayin' no to a peace offering. 
    Especially not when the Sheriff's offering that kind of quality. 
    Appreciate the gesture, Sheriff. One shot it is!"
    Millie, who'd been bracing for a fight, offered Jam a grateful smile. 
  - When Jam returns to the bar, both Charlaine and Krabat are gone. Jam first assumes that they
    just went to stretch their legs, but then he smells it. Ozone and a hint of clove.
    Someone had magicked them away.


# What of the given sceneries in the parent YAML does this chapter play in?
environment:
  - abandoned basement
  - Fangs and Fur

# Optional changes to characters
characters:
  The killer: DELETE
  Krabat:
    Krabat is tall and lean, with piercing black eyes and a shock of white hair that seems to defy gravity.
    He Appears to be in his late 30s, but is actually much older. He often wears dark, tailored clothing that 
    hints at a European origin. A faint scar snakes across his left cheek, adding to his air of mystery. He is 
    the same Krabat from the Slavic folktale of a young man who apprentices himself to a dark sorcerer.  However, 
    after all those centuries, Krabat is the powerful sorcerer himself. Krabat emigrated to America from Europe in 
    the 17th century.  He roamed the continent, using his magic to exploit and manipulate others.
    Officially, Krabat owns a curio shop filled with seemingly ordinary trinkets and antiques. However, his true 
    income comes from leveraging his magic for personal gain. Krabat is a master manipulator, able to weave 
    charm and intimidation with equal ease. He possesses a dry wit and a sardonic sense of humor.  
    Despite his outward charisma, there's a cold distance in his eyes, a hint of darkness lurking beneath the 
    surface. His true motives are shrouded in secrecy. He seems content with his life of luxury, but there's 
    a hint of restlessness in his eyes, a suggestion that he seeks something more.  Perhaps he craves a challenge, 
    or maybe he yearns for something he lost long ago. There's a simmering tension between Krabat and 
    Sheriff Jam Slate. Whether it stems from a past conflict, ideological differences, or a shared interest 
    in the alluring mayor, Anna Arborio, remains unclear.
