# Chapter specific configuration

# The beats for this chapter
story beats:
  - The chapter opens with foo...
  - bar...
  - foobar...
  - and so on until the last beat


# What of the given sceneries in the parent YAML does this chapter play in?
environment:
  Environment Name

# Optional changes to characters
characters:
  The killer: DELETE
